function out1 = T_IC_fun(in1)
%T_IC_FUN
%    OUT1 = T_IC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Nov-2020 16:56:34

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = q2+q3;
t8 = pi./3.0;
t6 = cos(t5);
t7 = sin(t5);
t9 = t5+t8;
t12 = t3.*5.404319552844595e+16;
t10 = cos(t9);
t11 = sin(t9);
t13 = t7.*2.669825385884536e+16;
t14 = t6.*4.382926039051794e+16;
t15 = -t13;
t16 = t12+t14+t15;
out1 = reshape([-t4.*t11,t2.*t11,-t10,0.0,-t4.*t10,t2.*t10,t11,0.0,t2,t4,0.0,0.0,t4.*t16.*(-1.110223024625157e-17),(t2.*t16)./9.007199254740992e+16,t6.*2.964101615137755e-1+t7.*4.866025403784439e-1+sin(q2).*(3.0./5.0)+7.0./1.0e+1,1.0],[4,4]);
