function b = b_fun_solution(in1,in2)
%B_FUN_SOLUTION
%    B = B_FUN_SOLUTION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Oct-2020 13:15:30

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q3);
t3 = dq1.^2;
t4 = q2.*2.0;
t5 = q3.*2.0;
t6 = sin(t4);
t7 = q3+t4;
t9 = t4+t5;
t8 = sin(t7);
t10 = sin(t9);
t11 = (t3.*t10)./3.2e+1;
b = [dq1.*(dq3.*t2.*1.2e+1+dq2.*t6.*3.6e+1+dq2.*t8.*2.4e+1+dq3.*t8.*1.2e+1+dq2.*t10.*5.0+dq3.*t10.*5.0).*(-1.0./8.0e+1);t11+t3.*t6.*(9.0./4.0e+1)+t3.*t8.*(3.0./2.0e+1)-dq3.^2.*t2.*(3.0./2.0e+1)-dq2.*dq3.*t2.*(3.0./1.0e+1);t11+t2.*t3.*(3.0./4.0e+1)+t3.*t8.*(3.0./4.0e+1)+dq2.^2.*t2.*(3.0./2.0e+1)];
