function g = g_fun_solution(in1)
%G_FUN_SOLUTION
%    G = G_FUN_SOLUTION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Oct-2020 13:15:30

q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2+q3;
t3 = cos(t2);
t4 = t3.*(9.81e+2./4.0e+2);
g = [0.0;t4+cos(q2).*8.829;t4];
