function M = M_fun_solution(in1)
%M_FUN_SOLUTION
%    M = M_FUN_SOLUTION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Oct-2020 13:15:30

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = q2.*2.0;
t4 = t2.*(3.0./2.0e+1);
t5 = t4+2.9e+1./4.0e+2;
M = reshape([t4+cos(q3.*2.0+t3)./3.2e+1+cos(q3+t3).*(3.0./2.0e+1)+cos(t3).*(9.0./4.0e+1)+2.61e+2./8.0e+2,0.0,0.0,0.0,t2.*(3.0./1.0e+1)+2.13e+2./4.0e+2,t5,0.0,t5,2.9e+1./4.0e+2],[3,3]);
